In [2]:
import tensorflow as tf
print(('Your tensorflow version: {0}').format(tf.__version__))

Your tensorflow version: 2.10.0


In [3]:
 A = tf.constant([[4,3], [6,1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1]])>

In [6]:
V = tf.Variable([[5,6], [9,8]])
V

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [9, 8]])>

In [11]:
av_concatenated = tf.concat(values=[A, V], axis=1)
av_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 5, 6],
       [6, 1, 9, 8]])>

In [12]:
tf.zeros(shape = [3,4])


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [24]:
t=tf.random.uniform(shape=[4,3], dtype=tf.float32)
t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0.2559203 , 0.8483367 , 0.3464409 ],
       [0.27261603, 0.18811202, 0.8665091 ],
       [0.96940506, 0.77035177, 0.43415463],
       [0.59138286, 0.24554586, 0.6054436 ]], dtype=float32)>

In [25]:
tensor_as_int = tf.cast(t, tf.int32)
tensor_as_int

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])>

In [26]:
a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [27]:
rows, columns = a.shape
rows, columns

(3, 4)